### ISSUE TITLE
Replace polling by GCM

### ISSUE THREAD

**Issue by Kaljurand** [Kaljurand/Diktofon#17]
Original [issue 16](https://code.google.com/p/diktofon/issues/detail?id=16) created by Kaljurand on 2012-06-30T23:04:35.000Z:

http://developer.android.com/guide/google/gcm/index.html

**Comment by marmistrz** [comment]
Please, do not use proprietary dependencies such as Play services.

Besides, what are push notifications needed for in your app?

**Comment by Kaljurand** [comment]
Agreed, Diktofon should not depend on Google Play Services.

Diktofon is typically used to transcribe longer audio recordings, where the transcription process is performed by a server and can take several hours. There should be an efficient way to inform the user once the transcription is ready and viewable in the app. The current approach is to wait for a certain period of time (derived directly from the length of the audio) and then poll a few times. Often this does not result in the desired outcome, so a better solution is needed.
