### ISSUE TITLE
new release?

### ISSUE THREAD

**Issue by dpocock** [Kaljurand/Diktofon#27]
Hi, could you tag a new release with the recent fixes I contributed?  I would like to publish a blog about how I use the app but I want to make sure people will be getting the latest version.

**Comment by Kaljurand** [comment]
I've tagged a new release, see https://github.com/Kaljurand/Diktofon/releases/tag/v0.9.82

I won't have time in the coming weeks to push it to Google Play though. Is this sufficient for you?

**Comment by dpocock** [comment]
F-Droid will automatically build it from the tag.  It would be nice to have on Google Play too, you will get a lot of hits when I link to it from my blog as it is syndicated to various planet sites.

**Comment by Kaljurand** [comment]
Version v0.9.83 (https://github.com/Kaljurand/Diktofon/releases/tag/v0.9.83) is now available on Google Play as well.
